import Product1 from "./product2.png";
import { nanoid } from "nanoid";

export const TopsaleData = [
  {
    id: nanoid(),
    img: Product1,
    price: "299 000 so’m",
    title: `Apple Airpods Pro simsiz quloqchin, Oq rangda`,
    order: `1230 ta buyurtma`,
    badge: "Yangilik",
  },
  {
    id: nanoid(),
    img: Product1,
    price: "16 114 285 so’m",
    title: `Apple Macbook Pro 13' 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB`,
    order: `230 ta buyurtma`,
    badge: "Top sale",
  },
  {
    id: nanoid(),
    img: Product1,
    price: "4 234 000 so’m",
    title: `Apple watch 4`,
    order: `543 ta buyurtma`,
    badge: "Yangilik",
  },
  {
    id: nanoid(),
    img: Product1,
    price: "1 340 000 so’m",
    title: `Robot - tozalagich Xiaomi Mi Robot`,
    order: `876 ta buyurtma`,
  },
  {
    id: nanoid(),
    img: Product1,
    price: "1 345 000 so’m",
    title: `Oynali Fotoaparat Canon EOS 6D Body`,
    order: `565 ta buyurtma`,
  },
  {
    id: nanoid(),
    img: Product1,
    price: "299 000 so’m",
    title: `Apple Airpods Pro simsiz quloqchin, Oq rangda`,
    order: `1230 ta buyurtma`,
    badge: "Yangilik",
  },
  {
    id: nanoid(),
    img: Product1,
    price: "16 114 285 so’m",
    title: `Apple Macbook Pro 13' 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB`,
    order: `230 ta buyurtma`,
  },
  {
    id: nanoid(),
    img: Product1,
    price: "4 234 000 so’m",
    title: `Apple watch 4`,
    order: `543 ta buyurtma`,
  },
  {
    id: nanoid(),
    img: Product1,
    price: "1 340 000 so’m",
    title: `Robot - tozalagich Xiaomi Mi Robot`,
    order: `876 ta buyurtma`,
    badge: "Top sale",
  },
  {
    id: nanoid(),
    img: Product1,
    price: "1 345 000 so’m",
    title: `Oynali Fotoaparat Canon EOS 6D Body`,
    order: `565 ta buyurtma`,
  },
  {
    id: nanoid(),
    img: Product1,
    price: "500 000 so’m", 
    title: `Yangi mahsulot`, 
    order: `20 ta buyurtma`, 
    badge: "Yangilik", 
  },
];
